binds:
- port: 3000
  listeners:
  - routes:
    - policies:
        cors:
          allowOrigins:
          - "*"
          allowHeaders:
          - mcp-protocol-version
          - content-type
          - cache-control
          - authorization
          exposeHeaders:
          - "Mcp-Session-Id"
        jwtAuth:
          mode: strict
          issuer: "chains-pilot"
          audiences: ["gateway.v244.net"]
          jwks:
            file: /jwks.json
      backends: []
